local buffer = require("string.buffer")

---@class ozone.Script
---@field rtdirs ozone.Script.RuntimeDir[]
---@field after_rtdirs ozone.Script.RuntimeDir[]
local Script = {}
---@private
Script.__index = Script

---@class ozone.Script.RuntimeDir
---@field path string

---@return self
function Script.new()
    return setmetatable({
        rtdirs = {},
        after_rtdirs = {},
    }, Script)
end

---@return string
function Script:tostring()
    local buf = buffer.new():put([[
-- Code generated by nvim-ozone
-- vim:ft=lua:readonly:nowrap
]])
    if #self.rtdirs > 0 then
        buf:put('vim.api.nvim_set_option_value("rtp", ')
        local rtp = {}
        for _, rtdir in ipairs(self.rtdirs) do
            table.insert(rtp, rtdir.path)
        end
        buf:putf("%q .. ", table.concat(rtp, ",") .. ",")
        buf:put('vim.api.nvim_get_option_value("rtp", {})')
        if #self.after_rtdirs > 0 then
            local after_rtp = {}
            for _, rtdir in ipairs(self.after_rtdirs) do
                table.insert(after_rtp, rtdir.path)
            end
            buf:putf(" .. %q", "," .. table.concat(after_rtp, ","))
        end
        buf:put(", {})\n")
    end
    buf:put([[
vim.opt.loadplugins = false
vim.cmd("runtime! plugin/**/*.{vim,lua}")
vim.cmd("augroup filetypedetect")
vim.cmd("runtime! ftdetect/*.{vim,lua}")
vim.cmd("augroup END")
]])

    return buf:tostring()
end

return Script
