local buffer = require("string.buffer")

---@class ozone.Script
---@field default_rtdirs ozone.Script.RuntimeDir[]
---@field rtdirs ozone.Script.RuntimeDir[]
---@field after_rtdirs ozone.Script.RuntimeDir[]
local Script = {}
---@private
Script.__index = Script

---@class ozone.Script.RuntimeDir
---@field path string
--- `(self.path)/plugin/**/*.{vim,lua}`
---@field plugin_files string[]
--- `(self.path)/ftdetect/*.{vim,lua}`
---@field ftdetect_files string[]

---@return self
function Script.new()
    return setmetatable({
        default_rtdirs = {},
        rtdirs = {},
        after_rtdirs = {},
    }, Script)
end

---@param buf string.buffer
---@param path string
---@return string.buffer
local function source(buf, path)
    return buf:putf('vim.api.nvim_cmd({ cmd = "source", args = { %q } }, {})\n', path)
end

---@param buf string.buffer
---@param name string
---@return string.buffer
local function augroup(buf, name)
    return buf:putf('vim.api.nvim_cmd({ cmd = "augroup", args = { %q } }, {})\n', name)
end

---@return string
function Script:tostring()
    local buf = buffer.new():put([[
-- Code generated by nvim-ozone
-- vim:ft=lua:readonly:nowrap
]])
    local all_rtdirs = {} ---@type ozone.Script.RuntimeDir[]
    for _, rtdirs in ipairs({ self.rtdirs, self.default_rtdirs, self.after_rtdirs }) do
        table.move(rtdirs, 1, #rtdirs, #all_rtdirs + 1, all_rtdirs)
    end

    buf:put('vim.api.nvim_set_option_value("loadplugins", false, {})\n')

    do
        local rtp = {} ---@type string[]
        for _, rtdir in ipairs(all_rtdirs) do
            table.insert(rtp, rtdir.path)
        end
        local saved = vim.o.runtimepath
        vim.opt.runtimepath = rtp --[[@as any]]
        buf:putf('vim.api.nvim_set_option_value("runtimepath", %q, {})\n', vim.o.runtimepath)
        vim.o.runtimepath = saved
    end

    for _, rtdir in ipairs(all_rtdirs) do
        for _, path in ipairs(rtdir.plugin_files) do
            source(buf, path)
        end
    end

    local all_ftdetect_files = {} ---@type string[]
    for _, rtdir in ipairs(all_rtdirs) do
        table.move(rtdir.ftdetect_files, 1, #rtdir.ftdetect_files, #all_ftdetect_files + 1, all_ftdetect_files)
    end
    if #all_ftdetect_files > 0 then
        augroup(buf, "filetypedetect")
        for _, path in ipairs(all_ftdetect_files) do
            source(buf, path)
        end
        augroup(buf, "END")
    end

    return buf:tostring()
end

return Script
