local buffer = require("string.buffer")

---@class ozone.Script
---@field rtp_prefix string[]
---@field rtp_suffix string[]
local Script = {}
---@private
Script.__index = Script

---@return self
function Script.new()
    return setmetatable({
        rtp_prefix = {},
        rtp_suffix = {},
    }, Script)
end

---@return string
function Script:tostring()
    local buf = buffer.new():put([[
-- Code generated by nvim-ozone
-- vim:ft=lua:readonly:nowrap
]])
    for _, path in ipairs(self.rtp_prefix) do
        buf:putf("vim.opt.runtimepath:prepend(%q)\n", path)
    end
    for _, path in ipairs(self.rtp_suffix) do
        buf:putf("vim.opt.runtimepath:append(%q)\n", path)
    end
    buf:put([[
vim.opt.loadplugins = false
vim.cmd("runtime! plugin/**/*.{vim,lua}")
vim.cmd("augroup filetypedetect")
vim.cmd("runtime! ftdetect/*.{vim,lua}")
vim.cmd("augroup END")
]])

    return buf:tostring()
end

return Script
