local buffer = require("string.buffer")

local coro = require("ozone.x.coro")
local fs = require("ozone.x.fs")

---@class ozone.PluginSpec
--- Plugin directory path
---@field path string

---@class ozone.Build
---@field private _plugins table<string, ozone.PluginSpec>
---@field private _output_path string
local Build = {}
---@private
Build.__index = Build

---@class ozone.Script
---@field rtp_prefix string[]
---@field rtp_suffix string[]
local Script = {}
---@private
Script.__index = Script

---@return self
function Build.new()
    return setmetatable({
        _plugins = {},
        _output_path = vim.fn.stdpath("data") .. "/ozone/main",
    }, Build)
end

---@param name string
---@param spec ozone.PluginSpec
---@return nil
function Build:add_plugin(name, spec)
    self._plugins[name] = spec
end

---@return string path
function Build:generate_script()
    local script = Script.new()
    for _, spec in pairs(self._plugins) do
        if fs.is_dir(spec.path) then
            table.insert(script.rtp_prefix, spec.path)
            if fs.is_dir(spec.path .. "/after") then
                table.insert(script.rtp_suffix, spec.path .. "/after")
            end
        end
    end
    assert(fs.create_dir_all(vim.fs.dirname(self._output_path)))
    assert(fs.write_file(self._output_path, script:tostring()))
    return self._output_path
end

---@return self
function Script.new()
    return setmetatable({
        rtp_prefix = {},
        rtp_suffix = {},
    }, Script)
end

---@return string
function Script:tostring()
    local buf = buffer.new():put([[
-- Code generated by nvim-ozone
-- vim:ft=lua:readonly:nowrap
]])
    for _, path in ipairs(self.rtp_prefix) do
        buf:putf("vim.opt.runtimepath:prepend(%q)\n", path)
    end
    for _, path in ipairs(self.rtp_suffix) do
        buf:putf("vim.opt.runtimepath:append(%q)\n", path)
    end
    buf:put([[
vim.opt.loadplugins = false
vim.cmd("runtime! plugin/**/*.{vim,lua}")
vim.cmd("augroup filetypedetect")
vim.cmd("runtime! ftdetect/*.{vim,lua}")
vim.cmd("augroup END")
]])

    return buf:tostring()
end

local build_instance = Build.new()

---@class ozone
local ozone = {
    ---@param specs table<string, ozone.PluginSpec>
    ---@return nil
    add = function(specs)
        for name, spec in pairs(specs) do
            build_instance:add_plugin(name, spec)
        end
    end,

    ---@return nil
    run = function()
        assert(vim.v.vim_did_enter == 0)
        local co = coro.spawn(function()
            -- TODO: evaluate all build scripts
            require("_build")
            local script = build_instance:generate_script()
            local chunk = loadfile(script)
            if chunk then
                chunk()
            end
        end)
        coro.join(co)
    end,
}

return ozone
