local foo_path = vim.fs.normalize(vim.fn.stdpath("data") .. "/ozone/_/foo")
local bar_path = vim.fs.normalize(vim.fn.stdpath("data") .. "/ozone/custom/bar")
local versioned_path = vim.fs.normalize(vim.fn.stdpath("data") .. "/ozone/_/versioned")
local runtime_path = vim.tbl_map(vim.fs.normalize, vim.opt.runtimepath:get())

assert(vim.g.foo_git_count == 1)
assert(vim.g.bar_git_count == 1)
assert(vim.g.versioned_git_count == 1)
assert(vim.tbl_contains(runtime_path, foo_path))
assert(vim.tbl_contains(runtime_path, bar_path))
assert(vim.tbl_contains(runtime_path, versioned_path))
assert(vim.uv.fs_stat(vim.fs.joinpath(foo_path, "plugin", "foo.lua")) ~= nil)
assert(vim.uv.fs_stat(vim.fs.joinpath(bar_path, "plugin", "bar.lua")) ~= nil)
assert(vim.uv.fs_stat(vim.fs.joinpath(versioned_path, "plugin", "versioned.lua")) ~= nil)
